name: CI Pipeline with ECR + GitOps

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ECR_URI }}:${IMAGE_TAG} .

    - name: Push to ECR
      run: |
        docker push ${{ secrets.ECR_URI }}:${IMAGE_TAG}

    # 🔥 NEW STEP (GitOps Integration)
    - name: Update GitOps Repo
      run: |
        git clone https://${{ secrets.GITOPS_REPO_TOKEN }}@github.com/<your-username>/pymongo-ops-deploy.git
        cd pymongo-ops-deploy/k8s

        sed -i "s|IMAGE_TAG|${IMAGE_TAG}|g" deployment.yaml

        git config user.name "github-actions"
        git config user.email "actions@github.com"

        git add .
        git commit -m "Update image to ${IMAGE_TAG}"
        git push